# Instalar en plugins de VSCode RestClient

@api                            = http://localhost:8080/api/secretary/newPatient
@apiNewPatient                  = http://localhost:8080/api/secretary/newPatient
@apiNewAppointment              = http://localhost:8080/api/doctor/newAppointment
@apiDeleteAppointment           = http://localhost:8080/api/doctor/deleteAppointment
@apiUpdateAppointment           = http://localhost:8080/api/doctor/updateAppointment
@apiViewAppointmentsByIdDoctor  = http://localhost:8080/api/doctor/viewAppointmentsByIdDoctor
@apiViewAllPatients             = http://localhost:8080/api/doctor/viewAllPatients 
@apiViewPatientById             = http://localhost:8080/api/doctor/viewPatientById 
@apiViewExpensesByIdDoctor      = http://localhost:8080/api/doctor/viewExpensesByIdDoctor 
@apiNewRadiography              = http://localhost:8080/api/doctor/newRadiography 






GET {{api}}

### create a patient
POST {{apiNewPatient}}
Content-Type: application/json

{
    "birthDate": "20130128",
    "curp": "REVE001019HNLYLDA2",
    "name": "Eduardo Reyna",
    "patientEmail": "eduardoreynav@gmail.com"

}


### create an appointment
POST {{apiNewAppointment}}
Content-Type: application/json

{
    "date": "20130128",
    "status": "Realizado",
    "patient_id": 1,
    "doctor_id": 3,
    "treatment_id": 23,
    "radiography_id": 3

}

### DELETE an appointment by id
DELETE {{apiDeleteAppointment}}
Content-Type: application/json

{
    "id_appointment": 17
}


### Update an appointment
PUT {{apiUpdateAppointment}}
Content-Type: application/json

{
    "id_appointment": "6",
    "date": "20130128",
    "status": "Pendiente",
    "patient_id": 1,
    "doctor_id": 1,
    "treatment_id": 23,
    "radiography_id": 3

}

### View appointments By Doctor Id
GET {{apiViewAppointmentsByIdDoctor}}
Content-Type: application/json

{
    "doctor_id": 3
}


### View All patients
GET {{apiViewAllPatients}}


### View patient By Id
GET {{apiViewPatientById}}
Content-Type: application/json

{
    "patient_id": 3
}


### View expendes By Doctor Id
GET {{apiViewExpensesByIdDoctor}}
Content-Type: application/json

{
    "doctor_id": 1
}


### subir radiografía
POST {{apiNewRadiography}}
Content-Type: application/json

{
    "image_name": "prueba", 
    "path": "C:/Users/Eduardo/ProyectosReact/UploadImages/nodejs-finterest/src/public/img/uploads/878a54f9-afdd-4665-881b-df6259796548.jpg",
    "patient_id": 1

}