@apiGetAppointments                            = http://localhost:8080/api/secretary/getAppointments
@apiUpdateAppointment                            = http://localhost:8080/api/secretary/updateAppointmentById
@apiDeleteAppointment                            = http://localhost:8080/api/secretary/deleteAppointmentById
@apiCreateAppointment                            = http://localhost:8080/api/secretary/createAppointment
@apiGetAllExpenses                            = http://localhost:8080/api/secretary/getExpenses
@apiupdateExpenseById                            = http://localhost:8080/api/secretary/updateExpenseById
@apiNewExpense                            = http://localhost:8080/api/secretary/newExpense
@apiNewPatient                            = http://localhost:8080/api/secretary/newPatient
@apiGetAllPatients                            = http://localhost:8080/api/secretary/getPatients
@apiDeletePatientById                          = http://localhost:8080/api/secretary/deletePatientById
@apiUpdatePatientById                          = http://localhost:8080/api/secretary/updatePatientById
##@apiGetAppointments
GET {{apiGetAppointments}}
Content-Type: application/json

{

}

###apiUpdateAppointment
PUT {{apiUpdateAppointment}}
Content-Type: application/json

{
    "appointmentID" :6,
    "status" : "Realizado",
    "date" : "03/15/22"
}

### apiDeleteAppointment
DELETE {{apiDeleteAppointment}}
Content-Type: application/json

{
    "appointmentID" :260

}


### apiCreateAppointment
POST {{apiCreateAppointment}}
Content-Type: application/json

{
    "date": "20160128",
    "status": "Pendiente",
    "patient_id": 1,
    "doctor_id": 3,
    "treatment_id": 23,
    "radiography_id": 3

}
### apiGetAllExpenses
GET  {{apiGetAllExpenses}}
Content-Type: application/json

{

}
### apiNewExpense 
POST {{apiNewExpense}}
Content-Type: application/json

{
    "date" : "20130628",
    "money" : 132.5,
    "description" : "Se compró agua oxigenada",
    "doctor_id" : 1

}
### apiNewPatient
POST {{apiNewPatient}}
Content-Type: application/json

{
    "birthDate" : "20130628",
    "curp" : "fsf2454fsd34564",
    "name" : "Fidencio botanero",
    "patientEmail" : "fidencio@gmail.com"

}
### apiNewPatient
PUT {{apiUpdatePatientById}}
Content-Type: application/json

{
    "patientID" : 1,
    "birthDate" : "20000512",
    "curp" : "GOTA820521HVZMLP02",
    "name" : "Arturo Tamayo",
    "patientEmail" : "Arturit.Tamayo@gmail.com"

}
### apiNewPatient
GET {{apiGetAllPatients}}
Content-Type: application/json

{


}
### deletePatientById
DELETE {{apiDeletePatientById}}
Content-Type: application/json

{
    "patientID" : 6

}

###apiupdateExpenseById
POST {{apiupdateExpenseById}}
Content-Type: application/json

{
    "expenseID" : 9,
    "money" : 647,
    "description" : "Se compraron comida los doctores jej",
    "date" : "20130628"

}

